[Breaking] Extend grammar.wrap to check constraints properly
JetBrains/MPS-extensions pull request #664
Opened 2023-10-05 11:35 UTC by HeikoBecker

Previously, if concept `A` contained concept `B` with an editor defined with grammar.rule with a grammar.wrap for `B`, constraints from `A` limiting occurrences of `B` were not taken into account when building the completion menu items. 

This PR fixes this issue.

The PR is a breaking change because it alters completion menus for all concepts that fall under the above description.

2023-10-05 12:02 UTC, alexanderpann requested changes
Nice work! Without tests although, this change looks risky. The code itselfs looks good to me. Can you create an editor test that checks the code completion menu for each entry for some different constraints? An example from a different test to get the content of the code completion menu: 

```
invoke action -> Backspace
....
SubstituteInfo si = (editor component.getSelectedCell()).getSubstituteInfo();
list<SubstituteAction> actions = si.getMatchingActions("", false);
assert actions.size == 4;
assert actions.any({ it => it.getMatchingText().equals("something"); });
```

2023-10-09 12:35 UTC, HeikoBecker commented
> Nice work! Without tests although, this change looks risky. The code itselfs looks good to me. Can you create an editor test that checks the code completion menu for each entry for some different constraints? An example from a different test to get the content of the code completion menu:
> 
> ```
> invoke action -> Backspace
> ....
> SubstituteInfo si = (editor component.getSelectedCell()).getSubstituteInfo();
> list<SubstituteAction> actions = si.getMatchingActions("", false);
> assert actions.size == 4;
> assert actions.any({ it => it.getMatchingText().equals("something"); });
> ```

Thanks for the tip! I have added tests for the canBeAncestor and canBeParent constraints in the latest commit.

2023-10-10 05:03 UTC, alexanderpann approved these changes

2023-10-10 05:12 UTC, merged

2023-10-30 13:30 UTC, markusvoelter commented
Cool!