Tables: Various fixes to table end cells in combination with insert and deletion handler
JetBrains/MPS-extensions pull request #974
Opened 2024-10-09 14:05 UTC by alexanderpann

@arimer to test the changes, please have a brief look at the MPS-Extensions [Tables Sandbox](http://127.0.0.1:63320/node?ref=r%3A7b909ba9-e58e-4fbd-8829-ecfbd89930fa%28de.slisson.mps.tables.sandbox%29%2F1397920687866914332) to check for broken stuff. I didn't add any delete or insert handlers there.

For proper testing, you can open https://github.com/IETS3/iets3.opensource/tree/bugfix/tables as a second project and check instances of the following concepts: DataTable, Sheet, LookupTable, DecTab.

When the default implementation for deletion is used (not derived from a header deletion handler), there is a differentiation between BACKSPACE (delete to the left of cursor) and DELETE (delete to the right of the cursor). For the derived delete actions we could create a followup ticket. For INSERT (enter) and INSERT_BEFORE (Shift + Enter) the same applies. For all actions this means that depending on the ACTION it modifies the row before the current row, the current row or the next row.  The left and right cell therefore modify different rows. Example:
DELETE on a left end cell deletes the current row since it is to the right of the cell, DELETE on a right end cell deletes the next row.

I didn't open a PR in IETS3 yet because without this PR the other PR doesn't build. I also added a few helper methods such as `Grid#setEndCellAction` that are unused in both repos as the moment but could be useful for other people.

- fixes https://github.com/JetBrains/MPS-extensions/issues/953
- fixes https://github.com/JetBrains/MPS-extensions/issues/955 in combination with https://github.com/IETS3/iets3.opensource/tree/bugfix/tables
- fixes https://github.com/JetBrains/MPS-extensions/issues/958

2024-10-10 09:52 UTC, arimer requested changes
Awesome refactoring 👍🏼 
Just some minor findings we should address before merging: 

- lets surround the whole logic inside the for loop with that[ header!=null](http://127.0.0.1:63320/node?ref=r%3A9eebd85f-0264-4bca-b8dc-0e1b71e196f7%28de.slisson.mps.tables.generator.template.main%40generator%29%2F244222589689910240) check
- Inside the ActionSettingAdapter, [this action](http://127.0.0.1:63320/node?ref=r%3Aea653f2d-c829-4182-b311-a544ef1f4c1f%28de.slisson.mps.tables.runtime.gridmodel%29%2F2399441400661704708) is not matching properly the case condition. I guess it should be a `setDeleteAction()`
- We are under `rightEnabled`. How about we rename [this variable](http://127.0.0.1:63320/node?ref=r%3Aea653f2d-c829-4182-b311-a544ef1f4c1f%28de.slisson.mps.tables.runtime.gridmodel%29%2F8156363746484502838)to something "right"
- This [HeaderReference key might](http://127.0.0.1:63320/node?ref=r%3Aea653f2d-c829-4182-b311-a544ef1f4c1f%28de.slisson.mps.tables.runtime.gridmodel%29%2F8271849212530108458) be not stable enought. Should we change the [getFallBackText()](http://127.0.0.1:63320/node?ref=r%3Aea653f2d-c829-4182-b311-a544ef1f4c1f%28de.slisson.mps.tables.runtime.gridmodel%29%2F1381472365344099779)to also take the `value` into account?

2024-10-10 11:54 UTC, arimer commented
The usecases in iest3 tables work as epected 💯 

However I gave up in understanding why a lookup table looks the way it looks like: 
<img width="102" alt="grafik" src="https://github.com/user-attachments/assets/6a406e6e-43cc-4e31-81a0-d1133c3102a6">

I don't know why  there is the 2 literal at all and why the end-cell is not show there, but this should not hinder us in merging.

2024-10-14 07:24 UTC, alexanderpann commented
> How about we rename [this variable](http://127.0.0.1:63320/node?ref=r%3Aea653f2d-c829-4182-b311-a544ef1f4c1f%28de.slisson.mps.tables.runtime.gridmodel%29%2F8156363746484502838)to something "right"
We still query the left create handler, so the name is fine.

> hould we change the [getFallBackText()](http://127.0.0.1:63320/node?ref=r%3Aea653f2d-c829-4182-b311-a544ef1f4c1f%28de.slisson.mps.tables.runtime.gridmodel%29%2F1381472365344099779)to also take the value into account?

I changed `SNodeHeaderReference#getFallBackText` to match `StringHeaderReference#getFallBackText`.

> I don't know why there is the 2 literal at all and why the end-cell is not show there, but this should not hinder us in merging.

Agree but you can't insert a row here anyway, so it is correct.

2024-10-14 07:32 UTC, arimer approved these changes
Thanks for the cleanup 👍🏼 

Changes look fine now.

2024-10-14 07:42 UTC, merged